<a href="https://colab.research.google.com/github/Moe-Arkar-Zaw/pytorch-bootcamp/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshape if we don't know the number of items using -1
my_torch2 = my_torch.reshape(-1, 5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch5 = my_torch3.reshape(-1, 5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch6 = my_torch5.reshape(2, -1)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
my_torch5[1] = 1212
my_torch5

tensor([[   0,    1,    2,    3,    4],
        [1212, 1212, 1212, 1212, 1212]])

In [8]:
my_torch6

tensor([[   0,    1,    2,    3,    4],
        [1212, 1212, 1212, 1212, 1212]])

In [9]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch7[5]

tensor(5)

In [11]:
#Grab Slice
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [13]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])