<a href="https://colab.research.google.com/github/Moe-Arkar-Zaw/pytorch-bootcamp/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])


In [4]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
torch.subtract(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
#Reminder Modulus
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [17]:
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [18]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [19]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
tensor_a

tensor([ 6,  8, 10, 12])