<a href="https://colab.research.google.com/github/Moe-Arkar-Zaw/pytorch-bootcamp/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("hello, world!")

hello, world!


In [3]:
import torch
import numpy as np

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.57470939, 0.64927015, 0.87728532, 0.28065476],
       [0.09413212, 0.55002296, 0.67601512, 0.48962576],
       [0.72930347, 0.92036007, 0.48336404, 0.48689456]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.3273, -1.3795, -0.9714,  0.9506],
        [-0.2845,  0.6616,  0.4424, -2.6369],
        [ 0.2295,  0.1353,  1.2878, -0.0259]])

In [8]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5747, 0.6493, 0.8773, 0.2807],
        [0.0941, 0.5500, 0.6760, 0.4896],
        [0.7293, 0.9204, 0.4834, 0.4869]], dtype=torch.float64)